### ISSUE TITLE
Integration von Gruppen

### ISSUE THREAD

**Issue by ChUrl** [hhu-propra2/abschlussprojekt-team-the-institute#50]
Jo Leute, ich wollte nochmal nachfragen was für Funktionen ihr für die Gruppenintegration verwendet/braucht. Wir sprechen uns momentan mit den Senioren ab und wollen eine einheitliche Api zur verfügung stellen. Deshalb wäre es praktisch, wenn ihr uns noch einmal sagen könntet welche Anfragen ihr macht und welche Informationen über die Gruppen ihr dann letztendlich verwendet.

**Comment by hanic101** [comment]
Wir arbeiten momentan mit den ganzen Gruppenobjekten und holen uns dort die Informationen raus. Aus dem Gruppenobjekt verwenden wir den Statuscode, die Gruppenmitglieder, den Titel und die GruppenId (eventuell den type).
Wir stellen einen Get Request mit der url: /gruppen2/api/updateGroups/"statuscode".

**Comment by ChUrl** [comment]
Ok also wie es aussieht ist es gar nicht nötig, dass beide Gruppenbildung-Gruppen eine einheitliche Schnittstelle bereitstellen. Je nachdem mit welcher Gruppe ihr gearbeitet habt könnt ihr das einfach beibehalten.
